id: P009540
initial_creation_type: ocr
source_metadata:
  id: bdr:W22023
  title: རི་བོ་རྩེ་ལྔའི་དཀར་ཆག་རབ་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    b0b88543cd2246ba95aff764cb473c86:
      image_group_id: I1KG13532
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
