id: I064E7044
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:27:51+00:00'
last_modified: '2022-06-08T11:45:17.729022+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22023
  title: རི་བོ་རྩེ་ལྔའི་དཀར་ཆག་རབ་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    44AF:
      image_group_id: I1KG13532
      title: ''
      total_pages: 238
      order: 1
      base_file: 44AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
